application:
  bindAddress: :8447
  production : false
  debug      : false
database:
  address : inventory-db:3306
  name    : inventory
  username: admin
  password: admin
authentication:
  authority   : https://algotiqa:8443/auth/realms/algotiqa
  clientId    : algotiqa-backend
  clientSecret: NOT_NEEDED
platform:
  system   : https://system-adapter:8449/api/system
  portfolio: https://portfolio-trader:8445/api/portfolio
  storage  : https://storage-manager:8452/api/storage
messaging:
  address : rabbitmq:5672
  username: admin
  password: admin
  journal:
    directory      : journal
    queueSize      : 1000
    compactMessages: 1000
    dbSpoolInterval: 2
provider:
  currency:
    baseUrl: https://api.freecurrencyapi.com/v1
    apiKey : PUT_YOUR_KEY_HERE
